name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 下载node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x
      - run: npm install -g pnpm  # 先安装pnpm
      - run: pnpm install  # 改为pnpm安装依赖
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: pnpm docs:build  # 改为pnpm执行构建
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./docs-dist
